### ISSUE TITLE
"z" is missing in code

### ISSUE THREAD

**Issue by avxmw** [kompetenzbolzen/oscad_gridfinity#1]
Hi and thanks for the project. I noticed "z Height in GridFinity units" in the documentation, however this isn't currently reflected in the code and seems to default to 3.

**Comment by kompetenzbolzen** [comment]
I'm not really sure what you mean. The third positional argument to `girdfinity()` `units_z` is indeed used and works as intended, at least for me. See attached files

![2023-01-26_22-23](https://user-images.githubusercontent.com/9308604/214954286-69bd2f24-f121-4efd-869c-ba5fb61bb9e1.png)

![2023-01-26_22-24](https://user-images.githubusercontent.com/9308604/214954486-bf5b1877-81f3-4221-b9b2-9b18e33d75e1.png)

**Comment by avxmw** [comment]
It works, yes. It's not exposed to be as easily edited as the other values though. I expected it to be also changeable here

![Screenshot_20230126_235030](https://user-images.githubusercontent.com/97355652/214968932-a2a6a67e-7680-40eb-9a93-6bb51799620f.png)

**Comment by kompetenzbolzen** [comment]
Ah now I see what you mean. The Documentation in the Readme only refers to `gridfinity()` in `gridfinity.scad`. It may differ for any objects using the library. I should make that clearer in the docs.

The bitstorage boxes still need some polish in general. They were hacked together pretty quickly.

I'll add the parameter as soon as I get to work on them again.
Thanks for your Input!
